<?xml version="1.0" encoding="utf-8"?><Database Name="INDUSTRIALV2" Class="IndustryEntityContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-3L8CV7U\SQLEXPRESS;Initial Catalog=INDUSTRIALV2;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="IndustrialConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Industrial" Member="Industrials">
    <Type Name="Industrial">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ID_Product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IndustrialLine" Member="IndustrialLines">
    <Type Name="IndustrialLine">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ID_Industrial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Material" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductionExhausts" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IndustrialStandard" Member="IndustrialStandards">
    <Type Name="IndustrialStandard">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Material" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Material" Member="Materials">
    <Type Name="Material">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentType" Member="PaymentTypes">
    <Type Name="PaymentType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ID_Unit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Purchase" Member="Purchases">
    <Type Name="Purchase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID_E_Buyer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_S_Seller" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerPO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoadingNote" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipmentNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipTo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DriverName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DriverLicense" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TruckNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CarrierNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CarrierName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SealNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BagsQty" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TareWeight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GrossWeight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NetWeight" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseLine" Member="PurchaseLines">
    <Type Name="PurchaseLine">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Material" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Package" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sRoleName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="sRoleDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sToolTip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sRoleNameArabic" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sale" Member="Sales">
    <Type Name="Sale">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsPayed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_PaymentType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_E_Seller" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_C_Buyer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaxNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="VAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NetTotal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ValueArabic" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SaleLine" Member="SaleLines">
    <Type Name="SaleLine">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UnitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Setting">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ArabicName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Department" Member="tbl_Departments">
    <Type Name="tbl_Department">
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Log" Member="tbl_Logs">
    <Type Name="tbl_Log">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Activity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ActivityParameters" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ActivityPage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ActivityDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Unit" Member="Units">
    <Type Name="Unit">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Userrole" Member="Userroles">
    <Type Name="Userrole">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bSave" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bEdit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bView" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bEnable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdentityNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BranchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Branch" Member="tbl_Branches">
    <Type Name="tbl_Branch">
      <Column Name="BranchID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="BranchDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>